#include "ParMap.h"

q_vec_int_t ch0 = { 0, 0, 0, { } };

void q_vec_int_put(q_vec_int_t * ch, vec_int_t v_f)
{
    while (1)
    {
        while (ch->q_size >= 16)
        {
        }
        if (ch->q_size < 16)
        {
            ch->q_mem[ch->q_head] = v_f;
            ch->q_head = (ch->q_head + 1) % 16;
            ch->q_size++;
            return;
        }
    }
}

vec_int_t q_vec_int_get(q_vec_int_t * ch)
{
    vec_int_t v_g;
    while (1)
    {
        while (ch->q_size <= 0)
        {
        }
        if (ch->q_size > 0)
        {
            v_g = ch->q_mem[ch->q_tail];
            ch->q_tail = (ch->q_tail + 1) % 16;
            ch->q_size--;
            return v_g;
        }
    }
}

q_vec_int_t ch1 = { 0, 0, 0, { } };

q_vec_int_t ch2 = { 0, 0, 0, { } };

q_vec_int_t ch3 = { 0, 0, 0, { } };

q_vec_int_t ch4 = { 0, 0, 0, { } };

q_vec_int_t ch5 = { 0, 0, 0, { } };

q_vec_int_t ch6 = { 0, 0, 0, { } };

q_vec_int_t ch7 = { 0, 0, 0, { } };

q_vec_int_t ch8 = { 0, 0, 0, { } };

q_vec_int_t ch9 = { 0, 0, 0, { } };

q_vec_int_t ch10 = { 0, 0, 0, { } };

q_vec_int_t ch11 = { 0, 0, 0, { } };

q_vec_int_t ch12 = { 0, 0, 0, { } };

q_vec_int_t ch13 = { 0, 0, 0, { } };

q_vec_int_t ch14 = { 0, 0, 0, { } };

q_vec_int_t ch15 = { 0, 0, 0, { } };

q_vec_int_t ch16 = { 0, 0, 0, { } };

q_vec_int_t ch17 = { 0, 0, 0, { } };

q_vec_int_t ch18 = { 0, 0, 0, { } };

q_vec_int_t ch19 = { 0, 0, 0, { } };

q_vec_int_t ch20 = { 0, 0, 0, { } };

q_vec_int_t ch21 = { 0, 0, 0, { } };

q_vec_int_t ch22 = { 0, 0, 0, { } };

q_vec_int_t ch23 = { 0, 0, 0, { } };

q_vec_int_t ch24 = { 0, 0, 0, { } };

q_vec_int_t ch25 = { 0, 0, 0, { } };

q_vec_int_t ch26 = { 0, 0, 0, { } };

q_vec_int_t ch27 = { 0, 0, 0, { } };

q_vec_int_t ch28 = { 0, 0, 0, { } };

q_vec_int_t ch29 = { 0, 0, 0, { } };

q_vec_int_t ch30 = { 0, 0, 0, { } };

q_vec_int_t ch31 = { 0, 0, 0, { } };

vec_int_t scalarProd_part_0(vec_int_t v_a)
{
    int v_b;
    v_b = v_a.size / 32;
    int v_c;
    v_c = 0 * v_b;
    vec_int_t v_d;
    v_d.size = v_a.size - v_c;
    v_d.elems = v_a.elems + v_c;
    vec_int_t v_e;
    v_e.size = v_b;
    v_e.elems = v_d.elems;
    q_vec_int_put(&ch0, v_e);
    int v_h;
    v_h = 1 * v_b;
    vec_int_t v_i;
    v_i.size = v_a.size - v_h;
    v_i.elems = v_a.elems + v_h;
    vec_int_t v_j;
    v_j.size = v_b;
    v_j.elems = v_i.elems;
    q_vec_int_put(&ch1, v_j);
    int v_k;
    v_k = 2 * v_b;
    vec_int_t v_l;
    v_l.size = v_a.size - v_k;
    v_l.elems = v_a.elems + v_k;
    vec_int_t v_m;
    v_m.size = v_b;
    v_m.elems = v_l.elems;
    q_vec_int_put(&ch2, v_m);
    int v_n;
    v_n = 3 * v_b;
    vec_int_t v_o;
    v_o.size = v_a.size - v_n;
    v_o.elems = v_a.elems + v_n;
    vec_int_t v_p;
    v_p.size = v_b;
    v_p.elems = v_o.elems;
    q_vec_int_put(&ch3, v_p);
    int v_q;
    v_q = 4 * v_b;
    vec_int_t v_r;
    v_r.size = v_a.size - v_q;
    v_r.elems = v_a.elems + v_q;
    vec_int_t v_s;
    v_s.size = v_b;
    v_s.elems = v_r.elems;
    q_vec_int_put(&ch4, v_s);
    int v_t;
    v_t = 5 * v_b;
    vec_int_t v_u;
    v_u.size = v_a.size - v_t;
    v_u.elems = v_a.elems + v_t;
    vec_int_t v_v;
    v_v.size = v_b;
    v_v.elems = v_u.elems;
    q_vec_int_put(&ch5, v_v);
    int v_w;
    v_w = 6 * v_b;
    vec_int_t v_x;
    v_x.size = v_a.size - v_w;
    v_x.elems = v_a.elems + v_w;
    vec_int_t v_y;
    v_y.size = v_b;
    v_y.elems = v_x.elems;
    q_vec_int_put(&ch6, v_y);
    int v_z;
    v_z = 7 * v_b;
    vec_int_t v_aa;
    v_aa.size = v_a.size - v_z;
    v_aa.elems = v_a.elems + v_z;
    vec_int_t v_ba;
    v_ba.size = v_b;
    v_ba.elems = v_aa.elems;
    q_vec_int_put(&ch7, v_ba);
    int v_ca;
    v_ca = 8 * v_b;
    vec_int_t v_da;
    v_da.size = v_a.size - v_ca;
    v_da.elems = v_a.elems + v_ca;
    vec_int_t v_ea;
    v_ea.size = v_b;
    v_ea.elems = v_da.elems;
    q_vec_int_put(&ch8, v_ea);
    int v_fa;
    v_fa = 9 * v_b;
    vec_int_t v_ga;
    v_ga.size = v_a.size - v_fa;
    v_ga.elems = v_a.elems + v_fa;
    vec_int_t v_ha;
    v_ha.size = v_b;
    v_ha.elems = v_ga.elems;
    q_vec_int_put(&ch9, v_ha);
    int v_ia;
    v_ia = 10 * v_b;
    vec_int_t v_ja;
    v_ja.size = v_a.size - v_ia;
    v_ja.elems = v_a.elems + v_ia;
    vec_int_t v_ka;
    v_ka.size = v_b;
    v_ka.elems = v_ja.elems;
    q_vec_int_put(&ch10, v_ka);
    int v_la;
    v_la = 11 * v_b;
    vec_int_t v_ma;
    v_ma.size = v_a.size - v_la;
    v_ma.elems = v_a.elems + v_la;
    vec_int_t v_na;
    v_na.size = v_b;
    v_na.elems = v_ma.elems;
    q_vec_int_put(&ch11, v_na);
    int v_oa;
    v_oa = 12 * v_b;
    vec_int_t v_pa;
    v_pa.size = v_a.size - v_oa;
    v_pa.elems = v_a.elems + v_oa;
    vec_int_t v_qa;
    v_qa.size = v_b;
    v_qa.elems = v_pa.elems;
    q_vec_int_put(&ch12, v_qa);
    int v_ra;
    v_ra = 13 * v_b;
    vec_int_t v_sa;
    v_sa.size = v_a.size - v_ra;
    v_sa.elems = v_a.elems + v_ra;
    vec_int_t v_ta;
    v_ta.size = v_b;
    v_ta.elems = v_sa.elems;
    q_vec_int_put(&ch13, v_ta);
    int v_ua;
    v_ua = 14 * v_b;
    vec_int_t v_va;
    v_va.size = v_a.size - v_ua;
    v_va.elems = v_a.elems + v_ua;
    vec_int_t v_wa;
    v_wa.size = v_b;
    v_wa.elems = v_va.elems;
    q_vec_int_put(&ch14, v_wa);
    int v_xa;
    v_xa = 15 * v_b;
    vec_int_t v_ya;
    v_ya.size = v_a.size - v_xa;
    v_ya.elems = v_a.elems + v_xa;
    vec_int_t v_za;
    v_za.size = v_b;
    v_za.elems = v_ya.elems;
    q_vec_int_put(&ch15, v_za);
    vec_int_t v_ab;
    v_ab = q_vec_int_get(&ch16);
    vec_int_t v_bb;
    v_bb = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_cb;
    v_cb.fst = v_ab;
    v_cb.snd = v_bb;
    vec_int_t v_db;
    v_db = q_vec_int_get(&ch18);
    vec_int_t v_eb;
    v_eb = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_fb;
    v_fb.fst = v_db;
    v_fb.snd = v_eb;
    vec_int_t v_gb;
    v_gb = q_vec_int_get(&ch20);
    vec_int_t v_hb;
    v_hb = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_ib;
    v_ib.fst = v_gb;
    v_ib.snd = v_hb;
    vec_int_t v_jb;
    v_jb = q_vec_int_get(&ch22);
    vec_int_t v_kb;
    v_kb = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_lb;
    v_lb.fst = v_jb;
    v_lb.snd = v_kb;
    vec_int_t v_mb;
    v_mb = q_vec_int_get(&ch24);
    vec_int_t v_nb;
    v_nb = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_ob;
    v_ob.fst = v_mb;
    v_ob.snd = v_nb;
    vec_int_t v_pb;
    v_pb = q_vec_int_get(&ch26);
    vec_int_t v_qb;
    v_qb = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_rb;
    v_rb.fst = v_pb;
    v_rb.snd = v_qb;
    vec_int_t v_sb;
    v_sb = q_vec_int_get(&ch28);
    vec_int_t v_tb;
    v_tb = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_ub;
    v_ub.fst = v_sb;
    v_ub.snd = v_tb;
    vec_int_t v_vb;
    v_vb = q_vec_int_get(&ch30);
    vec_int_t v_wb;
    v_wb = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_xb;
    v_xb.fst = v_vb;
    v_xb.snd = v_wb;
    vec_int_t v_yb;
    v_yb = q_vec_int_get(&ch16);
    vec_int_t v_zb;
    v_zb = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_ac;
    v_ac.fst = v_yb;
    v_ac.snd = v_zb;
    vec_int_t v_bc;
    v_bc = q_vec_int_get(&ch18);
    vec_int_t v_cc;
    v_cc = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_dc;
    v_dc.fst = v_bc;
    v_dc.snd = v_cc;
    vec_int_t v_ec;
    v_ec = q_vec_int_get(&ch20);
    vec_int_t v_fc;
    v_fc = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_gc;
    v_gc.fst = v_ec;
    v_gc.snd = v_fc;
    vec_int_t v_hc;
    v_hc = q_vec_int_get(&ch22);
    vec_int_t v_ic;
    v_ic = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_jc;
    v_jc.fst = v_hc;
    v_jc.snd = v_ic;
    vec_int_t v_kc;
    v_kc = q_vec_int_get(&ch24);
    vec_int_t v_lc;
    v_lc = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_mc;
    v_mc.fst = v_kc;
    v_mc.snd = v_lc;
    vec_int_t v_nc;
    v_nc = q_vec_int_get(&ch26);
    vec_int_t v_oc;
    v_oc = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_pc;
    v_pc.fst = v_nc;
    v_pc.snd = v_oc;
    vec_int_t v_qc;
    v_qc = q_vec_int_get(&ch28);
    vec_int_t v_rc;
    v_rc = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_sc;
    v_sc.fst = v_qc;
    v_sc.snd = v_rc;
    vec_int_t v_tc;
    v_tc = q_vec_int_get(&ch30);
    vec_int_t v_uc;
    v_uc = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_vc;
    v_vc.fst = v_tc;
    v_vc.snd = v_uc;
    pair_vec_int_vec_int_t v_wc;
    v_wc.fst = cat(v_cb);
    v_wc.snd = cat(v_dc);
    vec_int_t v_xc;
    v_xc = q_vec_int_get(&ch16);
    vec_int_t v_yc;
    v_yc = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_zc;
    v_zc.fst = v_xc;
    v_zc.snd = v_yc;
    vec_int_t v_ad;
    v_ad = q_vec_int_get(&ch18);
    vec_int_t v_bd;
    v_bd = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_cd;
    v_cd.fst = v_ad;
    v_cd.snd = v_bd;
    vec_int_t v_dd;
    v_dd = q_vec_int_get(&ch20);
    vec_int_t v_ed;
    v_ed = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_fd;
    v_fd.fst = v_dd;
    v_fd.snd = v_ed;
    vec_int_t v_gd;
    v_gd = q_vec_int_get(&ch22);
    vec_int_t v_hd;
    v_hd = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_id;
    v_id.fst = v_gd;
    v_id.snd = v_hd;
    vec_int_t v_jd;
    v_jd = q_vec_int_get(&ch24);
    vec_int_t v_kd;
    v_kd = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_ld;
    v_ld.fst = v_jd;
    v_ld.snd = v_kd;
    vec_int_t v_md;
    v_md = q_vec_int_get(&ch26);
    vec_int_t v_nd;
    v_nd = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_od;
    v_od.fst = v_md;
    v_od.snd = v_nd;
    vec_int_t v_pd;
    v_pd = q_vec_int_get(&ch28);
    vec_int_t v_qd;
    v_qd = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_rd;
    v_rd.fst = v_pd;
    v_rd.snd = v_qd;
    vec_int_t v_sd;
    v_sd = q_vec_int_get(&ch30);
    vec_int_t v_td;
    v_td = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_ud;
    v_ud.fst = v_sd;
    v_ud.snd = v_td;
    vec_int_t v_vd;
    v_vd = q_vec_int_get(&ch16);
    vec_int_t v_wd;
    v_wd = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_xd;
    v_xd.fst = v_vd;
    v_xd.snd = v_wd;
    vec_int_t v_yd;
    v_yd = q_vec_int_get(&ch18);
    vec_int_t v_zd;
    v_zd = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_ae;
    v_ae.fst = v_yd;
    v_ae.snd = v_zd;
    vec_int_t v_be;
    v_be = q_vec_int_get(&ch20);
    vec_int_t v_ce;
    v_ce = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_de;
    v_de.fst = v_be;
    v_de.snd = v_ce;
    vec_int_t v_ee;
    v_ee = q_vec_int_get(&ch22);
    vec_int_t v_fe;
    v_fe = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_ge;
    v_ge.fst = v_ee;
    v_ge.snd = v_fe;
    vec_int_t v_he;
    v_he = q_vec_int_get(&ch24);
    vec_int_t v_ie;
    v_ie = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_je;
    v_je.fst = v_he;
    v_je.snd = v_ie;
    vec_int_t v_ke;
    v_ke = q_vec_int_get(&ch26);
    vec_int_t v_le;
    v_le = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_me;
    v_me.fst = v_ke;
    v_me.snd = v_le;
    vec_int_t v_ne;
    v_ne = q_vec_int_get(&ch28);
    vec_int_t v_oe;
    v_oe = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_pe;
    v_pe.fst = v_ne;
    v_pe.snd = v_oe;
    vec_int_t v_qe;
    v_qe = q_vec_int_get(&ch30);
    vec_int_t v_re;
    v_re = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_se;
    v_se.fst = v_qe;
    v_se.snd = v_re;
    pair_vec_int_vec_int_t v_te;
    v_te.fst = cat(v_fd);
    v_te.snd = cat(v_ge);
    vec_int_t v_ue;
    v_ue = q_vec_int_get(&ch16);
    vec_int_t v_ve;
    v_ve = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_we;
    v_we.fst = v_ue;
    v_we.snd = v_ve;
    vec_int_t v_xe;
    v_xe = q_vec_int_get(&ch18);
    vec_int_t v_ye;
    v_ye = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_ze;
    v_ze.fst = v_xe;
    v_ze.snd = v_ye;
    vec_int_t v_af;
    v_af = q_vec_int_get(&ch20);
    vec_int_t v_bf;
    v_bf = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_cf;
    v_cf.fst = v_af;
    v_cf.snd = v_bf;
    vec_int_t v_df;
    v_df = q_vec_int_get(&ch22);
    vec_int_t v_ef;
    v_ef = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_ff;
    v_ff.fst = v_df;
    v_ff.snd = v_ef;
    vec_int_t v_gf;
    v_gf = q_vec_int_get(&ch24);
    vec_int_t v_hf;
    v_hf = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_if;
    v_if.fst = v_gf;
    v_if.snd = v_hf;
    vec_int_t v_jf;
    v_jf = q_vec_int_get(&ch26);
    vec_int_t v_kf;
    v_kf = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_lf;
    v_lf.fst = v_jf;
    v_lf.snd = v_kf;
    vec_int_t v_mf;
    v_mf = q_vec_int_get(&ch28);
    vec_int_t v_nf;
    v_nf = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_of;
    v_of.fst = v_mf;
    v_of.snd = v_nf;
    vec_int_t v_pf;
    v_pf = q_vec_int_get(&ch30);
    vec_int_t v_qf;
    v_qf = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_rf;
    v_rf.fst = v_pf;
    v_rf.snd = v_qf;
    vec_int_t v_sf;
    v_sf = q_vec_int_get(&ch16);
    vec_int_t v_tf;
    v_tf = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_uf;
    v_uf.fst = v_sf;
    v_uf.snd = v_tf;
    vec_int_t v_vf;
    v_vf = q_vec_int_get(&ch18);
    vec_int_t v_wf;
    v_wf = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_xf;
    v_xf.fst = v_vf;
    v_xf.snd = v_wf;
    vec_int_t v_yf;
    v_yf = q_vec_int_get(&ch20);
    vec_int_t v_zf;
    v_zf = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_ag;
    v_ag.fst = v_yf;
    v_ag.snd = v_zf;
    vec_int_t v_bg;
    v_bg = q_vec_int_get(&ch22);
    vec_int_t v_cg;
    v_cg = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_dg;
    v_dg.fst = v_bg;
    v_dg.snd = v_cg;
    vec_int_t v_eg;
    v_eg = q_vec_int_get(&ch24);
    vec_int_t v_fg;
    v_fg = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_gg;
    v_gg.fst = v_eg;
    v_gg.snd = v_fg;
    vec_int_t v_hg;
    v_hg = q_vec_int_get(&ch26);
    vec_int_t v_ig;
    v_ig = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_jg;
    v_jg.fst = v_hg;
    v_jg.snd = v_ig;
    vec_int_t v_kg;
    v_kg = q_vec_int_get(&ch28);
    vec_int_t v_lg;
    v_lg = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_mg;
    v_mg.fst = v_kg;
    v_mg.snd = v_lg;
    vec_int_t v_ng;
    v_ng = q_vec_int_get(&ch30);
    vec_int_t v_og;
    v_og = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_pg;
    v_pg.fst = v_ng;
    v_pg.snd = v_og;
    pair_vec_int_vec_int_t v_qg;
    v_qg.fst = cat(v_if);
    v_qg.snd = cat(v_jg);
    vec_int_t v_rg;
    v_rg = q_vec_int_get(&ch16);
    vec_int_t v_sg;
    v_sg = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_tg;
    v_tg.fst = v_rg;
    v_tg.snd = v_sg;
    vec_int_t v_ug;
    v_ug = q_vec_int_get(&ch18);
    vec_int_t v_vg;
    v_vg = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_wg;
    v_wg.fst = v_ug;
    v_wg.snd = v_vg;
    vec_int_t v_xg;
    v_xg = q_vec_int_get(&ch20);
    vec_int_t v_yg;
    v_yg = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_zg;
    v_zg.fst = v_xg;
    v_zg.snd = v_yg;
    vec_int_t v_ah;
    v_ah = q_vec_int_get(&ch22);
    vec_int_t v_bh;
    v_bh = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_ch;
    v_ch.fst = v_ah;
    v_ch.snd = v_bh;
    vec_int_t v_dh;
    v_dh = q_vec_int_get(&ch24);
    vec_int_t v_eh;
    v_eh = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_fh;
    v_fh.fst = v_dh;
    v_fh.snd = v_eh;
    vec_int_t v_gh;
    v_gh = q_vec_int_get(&ch26);
    vec_int_t v_hh;
    v_hh = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_ih;
    v_ih.fst = v_gh;
    v_ih.snd = v_hh;
    vec_int_t v_jh;
    v_jh = q_vec_int_get(&ch28);
    vec_int_t v_kh;
    v_kh = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_lh;
    v_lh.fst = v_jh;
    v_lh.snd = v_kh;
    vec_int_t v_mh;
    v_mh = q_vec_int_get(&ch30);
    vec_int_t v_nh;
    v_nh = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_oh;
    v_oh.fst = v_mh;
    v_oh.snd = v_nh;
    pair_vec_int_vec_int_t v_ph;
    v_ph.fst = cat(v_lh);
    v_ph.snd = cat(v_oh);
    vec_int_t v_qh;
    v_qh = q_vec_int_get(&ch16);
    vec_int_t v_rh;
    v_rh = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_sh;
    v_sh.fst = v_qh;
    v_sh.snd = v_rh;
    vec_int_t v_th;
    v_th = q_vec_int_get(&ch18);
    vec_int_t v_uh;
    v_uh = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_vh;
    v_vh.fst = v_th;
    v_vh.snd = v_uh;
    vec_int_t v_wh;
    v_wh = q_vec_int_get(&ch20);
    vec_int_t v_xh;
    v_xh = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_yh;
    v_yh.fst = v_wh;
    v_yh.snd = v_xh;
    vec_int_t v_zh;
    v_zh = q_vec_int_get(&ch22);
    vec_int_t v_ai;
    v_ai = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_bi;
    v_bi.fst = v_zh;
    v_bi.snd = v_ai;
    vec_int_t v_ci;
    v_ci = q_vec_int_get(&ch24);
    vec_int_t v_di;
    v_di = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_ei;
    v_ei.fst = v_ci;
    v_ei.snd = v_di;
    vec_int_t v_fi;
    v_fi = q_vec_int_get(&ch26);
    vec_int_t v_gi;
    v_gi = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_hi;
    v_hi.fst = v_fi;
    v_hi.snd = v_gi;
    vec_int_t v_ii;
    v_ii = q_vec_int_get(&ch28);
    vec_int_t v_ji;
    v_ji = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_ki;
    v_ki.fst = v_ii;
    v_ki.snd = v_ji;
    vec_int_t v_li;
    v_li = q_vec_int_get(&ch30);
    vec_int_t v_mi;
    v_mi = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_ni;
    v_ni.fst = v_li;
    v_ni.snd = v_mi;
    vec_int_t v_oi;
    v_oi = q_vec_int_get(&ch16);
    vec_int_t v_pi;
    v_pi = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_qi;
    v_qi.fst = v_oi;
    v_qi.snd = v_pi;
    vec_int_t v_ri;
    v_ri = q_vec_int_get(&ch18);
    vec_int_t v_si;
    v_si = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_ti;
    v_ti.fst = v_ri;
    v_ti.snd = v_si;
    vec_int_t v_ui;
    v_ui = q_vec_int_get(&ch20);
    vec_int_t v_vi;
    v_vi = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_wi;
    v_wi.fst = v_ui;
    v_wi.snd = v_vi;
    vec_int_t v_xi;
    v_xi = q_vec_int_get(&ch22);
    vec_int_t v_yi;
    v_yi = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_zi;
    v_zi.fst = v_xi;
    v_zi.snd = v_yi;
    vec_int_t v_aj;
    v_aj = q_vec_int_get(&ch24);
    vec_int_t v_bj;
    v_bj = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_cj;
    v_cj.fst = v_aj;
    v_cj.snd = v_bj;
    vec_int_t v_dj;
    v_dj = q_vec_int_get(&ch26);
    vec_int_t v_ej;
    v_ej = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_fj;
    v_fj.fst = v_dj;
    v_fj.snd = v_ej;
    vec_int_t v_gj;
    v_gj = q_vec_int_get(&ch28);
    vec_int_t v_hj;
    v_hj = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_ij;
    v_ij.fst = v_gj;
    v_ij.snd = v_hj;
    vec_int_t v_jj;
    v_jj = q_vec_int_get(&ch30);
    vec_int_t v_kj;
    v_kj = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_lj;
    v_lj.fst = v_jj;
    v_lj.snd = v_kj;
    pair_vec_int_vec_int_t v_mj;
    v_mj.fst = cat(v_sh);
    v_mj.snd = cat(v_ti);
    vec_int_t v_nj;
    v_nj = q_vec_int_get(&ch16);
    vec_int_t v_oj;
    v_oj = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_pj;
    v_pj.fst = v_nj;
    v_pj.snd = v_oj;
    vec_int_t v_qj;
    v_qj = q_vec_int_get(&ch18);
    vec_int_t v_rj;
    v_rj = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_sj;
    v_sj.fst = v_qj;
    v_sj.snd = v_rj;
    vec_int_t v_tj;
    v_tj = q_vec_int_get(&ch20);
    vec_int_t v_uj;
    v_uj = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_vj;
    v_vj.fst = v_tj;
    v_vj.snd = v_uj;
    vec_int_t v_wj;
    v_wj = q_vec_int_get(&ch22);
    vec_int_t v_xj;
    v_xj = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_yj;
    v_yj.fst = v_wj;
    v_yj.snd = v_xj;
    vec_int_t v_zj;
    v_zj = q_vec_int_get(&ch24);
    vec_int_t v_ak;
    v_ak = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_bk;
    v_bk.fst = v_zj;
    v_bk.snd = v_ak;
    vec_int_t v_ck;
    v_ck = q_vec_int_get(&ch26);
    vec_int_t v_dk;
    v_dk = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_ek;
    v_ek.fst = v_ck;
    v_ek.snd = v_dk;
    vec_int_t v_fk;
    v_fk = q_vec_int_get(&ch28);
    vec_int_t v_gk;
    v_gk = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_hk;
    v_hk.fst = v_fk;
    v_hk.snd = v_gk;
    vec_int_t v_ik;
    v_ik = q_vec_int_get(&ch30);
    vec_int_t v_jk;
    v_jk = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_kk;
    v_kk.fst = v_ik;
    v_kk.snd = v_jk;
    vec_int_t v_lk;
    v_lk = q_vec_int_get(&ch16);
    vec_int_t v_mk;
    v_mk = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_nk;
    v_nk.fst = v_lk;
    v_nk.snd = v_mk;
    vec_int_t v_ok;
    v_ok = q_vec_int_get(&ch18);
    vec_int_t v_pk;
    v_pk = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_qk;
    v_qk.fst = v_ok;
    v_qk.snd = v_pk;
    vec_int_t v_rk;
    v_rk = q_vec_int_get(&ch20);
    vec_int_t v_sk;
    v_sk = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_tk;
    v_tk.fst = v_rk;
    v_tk.snd = v_sk;
    vec_int_t v_uk;
    v_uk = q_vec_int_get(&ch22);
    vec_int_t v_vk;
    v_vk = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_wk;
    v_wk.fst = v_uk;
    v_wk.snd = v_vk;
    vec_int_t v_xk;
    v_xk = q_vec_int_get(&ch24);
    vec_int_t v_yk;
    v_yk = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_zk;
    v_zk.fst = v_xk;
    v_zk.snd = v_yk;
    vec_int_t v_al;
    v_al = q_vec_int_get(&ch26);
    vec_int_t v_bl;
    v_bl = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_cl;
    v_cl.fst = v_al;
    v_cl.snd = v_bl;
    vec_int_t v_dl;
    v_dl = q_vec_int_get(&ch28);
    vec_int_t v_el;
    v_el = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_fl;
    v_fl.fst = v_dl;
    v_fl.snd = v_el;
    vec_int_t v_gl;
    v_gl = q_vec_int_get(&ch30);
    vec_int_t v_hl;
    v_hl = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_il;
    v_il.fst = v_gl;
    v_il.snd = v_hl;
    pair_vec_int_vec_int_t v_jl;
    v_jl.fst = cat(v_vj);
    v_jl.snd = cat(v_wk);
    vec_int_t v_kl;
    v_kl = q_vec_int_get(&ch16);
    vec_int_t v_ll;
    v_ll = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_ml;
    v_ml.fst = v_kl;
    v_ml.snd = v_ll;
    vec_int_t v_nl;
    v_nl = q_vec_int_get(&ch18);
    vec_int_t v_ol;
    v_ol = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_pl;
    v_pl.fst = v_nl;
    v_pl.snd = v_ol;
    vec_int_t v_ql;
    v_ql = q_vec_int_get(&ch20);
    vec_int_t v_rl;
    v_rl = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_sl;
    v_sl.fst = v_ql;
    v_sl.snd = v_rl;
    vec_int_t v_tl;
    v_tl = q_vec_int_get(&ch22);
    vec_int_t v_ul;
    v_ul = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_vl;
    v_vl.fst = v_tl;
    v_vl.snd = v_ul;
    vec_int_t v_wl;
    v_wl = q_vec_int_get(&ch24);
    vec_int_t v_xl;
    v_xl = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_yl;
    v_yl.fst = v_wl;
    v_yl.snd = v_xl;
    vec_int_t v_zl;
    v_zl = q_vec_int_get(&ch26);
    vec_int_t v_am;
    v_am = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_bm;
    v_bm.fst = v_zl;
    v_bm.snd = v_am;
    vec_int_t v_cm;
    v_cm = q_vec_int_get(&ch28);
    vec_int_t v_dm;
    v_dm = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_em;
    v_em.fst = v_cm;
    v_em.snd = v_dm;
    vec_int_t v_fm;
    v_fm = q_vec_int_get(&ch30);
    vec_int_t v_gm;
    v_gm = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_hm;
    v_hm.fst = v_fm;
    v_hm.snd = v_gm;
    vec_int_t v_im;
    v_im = q_vec_int_get(&ch16);
    vec_int_t v_jm;
    v_jm = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_km;
    v_km.fst = v_im;
    v_km.snd = v_jm;
    vec_int_t v_lm;
    v_lm = q_vec_int_get(&ch18);
    vec_int_t v_mm;
    v_mm = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_nm;
    v_nm.fst = v_lm;
    v_nm.snd = v_mm;
    vec_int_t v_om;
    v_om = q_vec_int_get(&ch20);
    vec_int_t v_pm;
    v_pm = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_qm;
    v_qm.fst = v_om;
    v_qm.snd = v_pm;
    vec_int_t v_rm;
    v_rm = q_vec_int_get(&ch22);
    vec_int_t v_sm;
    v_sm = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_tm;
    v_tm.fst = v_rm;
    v_tm.snd = v_sm;
    vec_int_t v_um;
    v_um = q_vec_int_get(&ch24);
    vec_int_t v_vm;
    v_vm = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_wm;
    v_wm.fst = v_um;
    v_wm.snd = v_vm;
    vec_int_t v_xm;
    v_xm = q_vec_int_get(&ch26);
    vec_int_t v_ym;
    v_ym = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_zm;
    v_zm.fst = v_xm;
    v_zm.snd = v_ym;
    vec_int_t v_an;
    v_an = q_vec_int_get(&ch28);
    vec_int_t v_bn;
    v_bn = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_cn;
    v_cn.fst = v_an;
    v_cn.snd = v_bn;
    vec_int_t v_dn;
    v_dn = q_vec_int_get(&ch30);
    vec_int_t v_en;
    v_en = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_fn;
    v_fn.fst = v_dn;
    v_fn.snd = v_en;
    pair_vec_int_vec_int_t v_gn;
    v_gn.fst = cat(v_yl);
    v_gn.snd = cat(v_zm);
    vec_int_t v_hn;
    v_hn = q_vec_int_get(&ch16);
    vec_int_t v_in;
    v_in = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_jn;
    v_jn.fst = v_hn;
    v_jn.snd = v_in;
    vec_int_t v_kn;
    v_kn = q_vec_int_get(&ch18);
    vec_int_t v_ln;
    v_ln = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_mn;
    v_mn.fst = v_kn;
    v_mn.snd = v_ln;
    vec_int_t v_nn;
    v_nn = q_vec_int_get(&ch20);
    vec_int_t v_on;
    v_on = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_pn;
    v_pn.fst = v_nn;
    v_pn.snd = v_on;
    vec_int_t v_qn;
    v_qn = q_vec_int_get(&ch22);
    vec_int_t v_rn;
    v_rn = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_sn;
    v_sn.fst = v_qn;
    v_sn.snd = v_rn;
    vec_int_t v_tn;
    v_tn = q_vec_int_get(&ch24);
    vec_int_t v_un;
    v_un = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_vn;
    v_vn.fst = v_tn;
    v_vn.snd = v_un;
    vec_int_t v_wn;
    v_wn = q_vec_int_get(&ch26);
    vec_int_t v_xn;
    v_xn = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_yn;
    v_yn.fst = v_wn;
    v_yn.snd = v_xn;
    vec_int_t v_zn;
    v_zn = q_vec_int_get(&ch28);
    vec_int_t v_ao;
    v_ao = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_bo;
    v_bo.fst = v_zn;
    v_bo.snd = v_ao;
    vec_int_t v_co;
    v_co = q_vec_int_get(&ch30);
    vec_int_t v_do;
    v_do = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_eo;
    v_eo.fst = v_co;
    v_eo.snd = v_do;
    pair_vec_int_vec_int_t v_fo;
    v_fo.fst = cat(v_bo);
    v_fo.snd = cat(v_eo);
    pair_vec_int_vec_int_t v_go;
    v_go.fst = cat(v_wc);
    v_go.snd = cat(v_jl);
    vec_int_t v_ho;
    v_ho = q_vec_int_get(&ch16);
    vec_int_t v_io;
    v_io = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_jo;
    v_jo.fst = v_ho;
    v_jo.snd = v_io;
    vec_int_t v_ko;
    v_ko = q_vec_int_get(&ch18);
    vec_int_t v_lo;
    v_lo = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_mo;
    v_mo.fst = v_ko;
    v_mo.snd = v_lo;
    vec_int_t v_no;
    v_no = q_vec_int_get(&ch20);
    vec_int_t v_oo;
    v_oo = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_po;
    v_po.fst = v_no;
    v_po.snd = v_oo;
    vec_int_t v_qo;
    v_qo = q_vec_int_get(&ch22);
    vec_int_t v_ro;
    v_ro = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_so;
    v_so.fst = v_qo;
    v_so.snd = v_ro;
    vec_int_t v_to;
    v_to = q_vec_int_get(&ch24);
    vec_int_t v_uo;
    v_uo = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_vo;
    v_vo.fst = v_to;
    v_vo.snd = v_uo;
    vec_int_t v_wo;
    v_wo = q_vec_int_get(&ch26);
    vec_int_t v_xo;
    v_xo = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_yo;
    v_yo.fst = v_wo;
    v_yo.snd = v_xo;
    vec_int_t v_zo;
    v_zo = q_vec_int_get(&ch28);
    vec_int_t v_ap;
    v_ap = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_bp;
    v_bp.fst = v_zo;
    v_bp.snd = v_ap;
    vec_int_t v_cp;
    v_cp = q_vec_int_get(&ch30);
    vec_int_t v_dp;
    v_dp = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_ep;
    v_ep.fst = v_cp;
    v_ep.snd = v_dp;
    vec_int_t v_fp;
    v_fp = q_vec_int_get(&ch16);
    vec_int_t v_gp;
    v_gp = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_hp;
    v_hp.fst = v_fp;
    v_hp.snd = v_gp;
    vec_int_t v_ip;
    v_ip = q_vec_int_get(&ch18);
    vec_int_t v_jp;
    v_jp = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_kp;
    v_kp.fst = v_ip;
    v_kp.snd = v_jp;
    vec_int_t v_lp;
    v_lp = q_vec_int_get(&ch20);
    vec_int_t v_mp;
    v_mp = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_np;
    v_np.fst = v_lp;
    v_np.snd = v_mp;
    vec_int_t v_op;
    v_op = q_vec_int_get(&ch22);
    vec_int_t v_pp;
    v_pp = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_qp;
    v_qp.fst = v_op;
    v_qp.snd = v_pp;
    vec_int_t v_rp;
    v_rp = q_vec_int_get(&ch24);
    vec_int_t v_sp;
    v_sp = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_tp;
    v_tp.fst = v_rp;
    v_tp.snd = v_sp;
    vec_int_t v_up;
    v_up = q_vec_int_get(&ch26);
    vec_int_t v_vp;
    v_vp = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_wp;
    v_wp.fst = v_up;
    v_wp.snd = v_vp;
    vec_int_t v_xp;
    v_xp = q_vec_int_get(&ch28);
    vec_int_t v_yp;
    v_yp = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_zp;
    v_zp.fst = v_xp;
    v_zp.snd = v_yp;
    vec_int_t v_aq;
    v_aq = q_vec_int_get(&ch30);
    vec_int_t v_bq;
    v_bq = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_cq;
    v_cq.fst = v_aq;
    v_cq.snd = v_bq;
    pair_vec_int_vec_int_t v_dq;
    v_dq.fst = cat(v_jo);
    v_dq.snd = cat(v_kp);
    vec_int_t v_eq;
    v_eq = q_vec_int_get(&ch16);
    vec_int_t v_fq;
    v_fq = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_gq;
    v_gq.fst = v_eq;
    v_gq.snd = v_fq;
    vec_int_t v_hq;
    v_hq = q_vec_int_get(&ch18);
    vec_int_t v_iq;
    v_iq = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_jq;
    v_jq.fst = v_hq;
    v_jq.snd = v_iq;
    vec_int_t v_kq;
    v_kq = q_vec_int_get(&ch20);
    vec_int_t v_lq;
    v_lq = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_mq;
    v_mq.fst = v_kq;
    v_mq.snd = v_lq;
    vec_int_t v_nq;
    v_nq = q_vec_int_get(&ch22);
    vec_int_t v_oq;
    v_oq = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_pq;
    v_pq.fst = v_nq;
    v_pq.snd = v_oq;
    vec_int_t v_qq;
    v_qq = q_vec_int_get(&ch24);
    vec_int_t v_rq;
    v_rq = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_sq;
    v_sq.fst = v_qq;
    v_sq.snd = v_rq;
    vec_int_t v_tq;
    v_tq = q_vec_int_get(&ch26);
    vec_int_t v_uq;
    v_uq = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_vq;
    v_vq.fst = v_tq;
    v_vq.snd = v_uq;
    vec_int_t v_wq;
    v_wq = q_vec_int_get(&ch28);
    vec_int_t v_xq;
    v_xq = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_yq;
    v_yq.fst = v_wq;
    v_yq.snd = v_xq;
    vec_int_t v_zq;
    v_zq = q_vec_int_get(&ch30);
    vec_int_t v_ar;
    v_ar = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_br;
    v_br.fst = v_zq;
    v_br.snd = v_ar;
    vec_int_t v_cr;
    v_cr = q_vec_int_get(&ch16);
    vec_int_t v_dr;
    v_dr = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_er;
    v_er.fst = v_cr;
    v_er.snd = v_dr;
    vec_int_t v_fr;
    v_fr = q_vec_int_get(&ch18);
    vec_int_t v_gr;
    v_gr = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_hr;
    v_hr.fst = v_fr;
    v_hr.snd = v_gr;
    vec_int_t v_ir;
    v_ir = q_vec_int_get(&ch20);
    vec_int_t v_jr;
    v_jr = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_kr;
    v_kr.fst = v_ir;
    v_kr.snd = v_jr;
    vec_int_t v_lr;
    v_lr = q_vec_int_get(&ch22);
    vec_int_t v_mr;
    v_mr = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_nr;
    v_nr.fst = v_lr;
    v_nr.snd = v_mr;
    vec_int_t v_or;
    v_or = q_vec_int_get(&ch24);
    vec_int_t v_pr;
    v_pr = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_qr;
    v_qr.fst = v_or;
    v_qr.snd = v_pr;
    vec_int_t v_rr;
    v_rr = q_vec_int_get(&ch26);
    vec_int_t v_sr;
    v_sr = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_tr;
    v_tr.fst = v_rr;
    v_tr.snd = v_sr;
    vec_int_t v_ur;
    v_ur = q_vec_int_get(&ch28);
    vec_int_t v_vr;
    v_vr = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_wr;
    v_wr.fst = v_ur;
    v_wr.snd = v_vr;
    vec_int_t v_xr;
    v_xr = q_vec_int_get(&ch30);
    vec_int_t v_yr;
    v_yr = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_zr;
    v_zr.fst = v_xr;
    v_zr.snd = v_yr;
    pair_vec_int_vec_int_t v_as;
    v_as.fst = cat(v_mq);
    v_as.snd = cat(v_nr);
    vec_int_t v_bs;
    v_bs = q_vec_int_get(&ch16);
    vec_int_t v_cs;
    v_cs = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_ds;
    v_ds.fst = v_bs;
    v_ds.snd = v_cs;
    vec_int_t v_es;
    v_es = q_vec_int_get(&ch18);
    vec_int_t v_fs;
    v_fs = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_gs;
    v_gs.fst = v_es;
    v_gs.snd = v_fs;
    vec_int_t v_hs;
    v_hs = q_vec_int_get(&ch20);
    vec_int_t v_is;
    v_is = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_js;
    v_js.fst = v_hs;
    v_js.snd = v_is;
    vec_int_t v_ks;
    v_ks = q_vec_int_get(&ch22);
    vec_int_t v_ls;
    v_ls = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_ms;
    v_ms.fst = v_ks;
    v_ms.snd = v_ls;
    vec_int_t v_ns;
    v_ns = q_vec_int_get(&ch24);
    vec_int_t v_os;
    v_os = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_ps;
    v_ps.fst = v_ns;
    v_ps.snd = v_os;
    vec_int_t v_qs;
    v_qs = q_vec_int_get(&ch26);
    vec_int_t v_rs;
    v_rs = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_ss;
    v_ss.fst = v_qs;
    v_ss.snd = v_rs;
    vec_int_t v_ts;
    v_ts = q_vec_int_get(&ch28);
    vec_int_t v_us;
    v_us = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_vs;
    v_vs.fst = v_ts;
    v_vs.snd = v_us;
    vec_int_t v_ws;
    v_ws = q_vec_int_get(&ch30);
    vec_int_t v_xs;
    v_xs = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_ys;
    v_ys.fst = v_ws;
    v_ys.snd = v_xs;
    vec_int_t v_zs;
    v_zs = q_vec_int_get(&ch16);
    vec_int_t v_at;
    v_at = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_bt;
    v_bt.fst = v_zs;
    v_bt.snd = v_at;
    vec_int_t v_ct;
    v_ct = q_vec_int_get(&ch18);
    vec_int_t v_dt;
    v_dt = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_et;
    v_et.fst = v_ct;
    v_et.snd = v_dt;
    vec_int_t v_ft;
    v_ft = q_vec_int_get(&ch20);
    vec_int_t v_gt;
    v_gt = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_ht;
    v_ht.fst = v_ft;
    v_ht.snd = v_gt;
    vec_int_t v_it;
    v_it = q_vec_int_get(&ch22);
    vec_int_t v_jt;
    v_jt = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_kt;
    v_kt.fst = v_it;
    v_kt.snd = v_jt;
    vec_int_t v_lt;
    v_lt = q_vec_int_get(&ch24);
    vec_int_t v_mt;
    v_mt = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_nt;
    v_nt.fst = v_lt;
    v_nt.snd = v_mt;
    vec_int_t v_ot;
    v_ot = q_vec_int_get(&ch26);
    vec_int_t v_pt;
    v_pt = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_qt;
    v_qt.fst = v_ot;
    v_qt.snd = v_pt;
    vec_int_t v_rt;
    v_rt = q_vec_int_get(&ch28);
    vec_int_t v_st;
    v_st = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_tt;
    v_tt.fst = v_rt;
    v_tt.snd = v_st;
    vec_int_t v_ut;
    v_ut = q_vec_int_get(&ch30);
    vec_int_t v_vt;
    v_vt = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_wt;
    v_wt.fst = v_ut;
    v_wt.snd = v_vt;
    pair_vec_int_vec_int_t v_xt;
    v_xt.fst = cat(v_ps);
    v_xt.snd = cat(v_qt);
    vec_int_t v_yt;
    v_yt = q_vec_int_get(&ch16);
    vec_int_t v_zt;
    v_zt = q_vec_int_get(&ch17);
    pair_vec_int_vec_int_t v_au;
    v_au.fst = v_yt;
    v_au.snd = v_zt;
    vec_int_t v_bu;
    v_bu = q_vec_int_get(&ch18);
    vec_int_t v_cu;
    v_cu = q_vec_int_get(&ch19);
    pair_vec_int_vec_int_t v_du;
    v_du.fst = v_bu;
    v_du.snd = v_cu;
    vec_int_t v_eu;
    v_eu = q_vec_int_get(&ch20);
    vec_int_t v_fu;
    v_fu = q_vec_int_get(&ch21);
    pair_vec_int_vec_int_t v_gu;
    v_gu.fst = v_eu;
    v_gu.snd = v_fu;
    vec_int_t v_hu;
    v_hu = q_vec_int_get(&ch22);
    vec_int_t v_iu;
    v_iu = q_vec_int_get(&ch23);
    pair_vec_int_vec_int_t v_ju;
    v_ju.fst = v_hu;
    v_ju.snd = v_iu;
    vec_int_t v_ku;
    v_ku = q_vec_int_get(&ch24);
    vec_int_t v_lu;
    v_lu = q_vec_int_get(&ch25);
    pair_vec_int_vec_int_t v_mu;
    v_mu.fst = v_ku;
    v_mu.snd = v_lu;
    vec_int_t v_nu;
    v_nu = q_vec_int_get(&ch26);
    vec_int_t v_ou;
    v_ou = q_vec_int_get(&ch27);
    pair_vec_int_vec_int_t v_pu;
    v_pu.fst = v_nu;
    v_pu.snd = v_ou;
    vec_int_t v_qu;
    v_qu = q_vec_int_get(&ch28);
    vec_int_t v_ru;
    v_ru = q_vec_int_get(&ch29);
    pair_vec_int_vec_int_t v_su;
    v_su.fst = v_qu;
    v_su.snd = v_ru;
    vec_int_t v_tu;
    v_tu = q_vec_int_get(&ch30);
    vec_int_t v_uu;
    v_uu = q_vec_int_get(&ch31);
    pair_vec_int_vec_int_t v_vu;
    v_vu.fst = v_tu;
    v_vu.snd = v_uu;
    pair_vec_int_vec_int_t v_wu;
    v_wu.fst = cat(v_su);
    v_wu.snd = cat(v_vu);
    pair_vec_int_vec_int_t v_xu;
    v_xu.fst = cat(v_xt);
    v_xu.snd = cat(v_wu);
    pair_vec_int_vec_int_t v_yu;
    v_yu.fst = cat(v_go);
    v_yu.snd = cat(v_xu);
    return cat(v_yu);
}

unit_t scalarProd_part_1()
{
    vec_int_t v_zu;
    v_zu = q_vec_int_get(&ch0);
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    q_vec_int_put(&ch16, prod(v_zu));
    return Unit;
}

unit_t scalarProd_part_2()
{
    vec_int_t v_av;
    v_av = q_vec_int_get(&ch1);
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    q_vec_int_put(&ch17, prod(v_av));
    return Unit;
}

unit_t scalarProd_part_3()
{
    vec_int_t v_bv;
    v_bv = q_vec_int_get(&ch2);
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    q_vec_int_put(&ch18, prod(v_bv));
    return Unit;
}

unit_t scalarProd_part_4()
{
    vec_int_t v_cv;
    v_cv = q_vec_int_get(&ch3);
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    q_vec_int_put(&ch19, prod(v_cv));
    return Unit;
}

unit_t scalarProd_part_5()
{
    vec_int_t v_dv;
    v_dv = q_vec_int_get(&ch4);
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    q_vec_int_put(&ch20, prod(v_dv));
    return Unit;
}

unit_t scalarProd_part_6()
{
    vec_int_t v_ev;
    v_ev = q_vec_int_get(&ch5);
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    q_vec_int_put(&ch21, prod(v_ev));
    return Unit;
}

unit_t scalarProd_part_7()
{
    vec_int_t v_fv;
    v_fv = q_vec_int_get(&ch6);
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    q_vec_int_put(&ch22, prod(v_fv));
    return Unit;
}

unit_t scalarProd_part_8()
{
    vec_int_t v_gv;
    v_gv = q_vec_int_get(&ch7);
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    q_vec_int_put(&ch23, prod(v_gv));
    return Unit;
}

unit_t scalarProd_part_9()
{
    vec_int_t v_hv;
    v_hv = q_vec_int_get(&ch8);
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    q_vec_int_put(&ch24, prod(v_hv));
    return Unit;
}

unit_t scalarProd_part_10()
{
    vec_int_t v_iv;
    v_iv = q_vec_int_get(&ch9);
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    q_vec_int_put(&ch25, prod(v_iv));
    return Unit;
}

unit_t scalarProd_part_11()
{
    vec_int_t v_jv;
    v_jv = q_vec_int_get(&ch10);
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    q_vec_int_put(&ch26, prod(v_jv));
    return Unit;
}

unit_t scalarProd_part_12()
{
    vec_int_t v_kv;
    v_kv = q_vec_int_get(&ch11);
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    q_vec_int_put(&ch27, prod(v_kv));
    return Unit;
}

unit_t scalarProd_part_13()
{
    vec_int_t v_lv;
    v_lv = q_vec_int_get(&ch12);
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    q_vec_int_put(&ch28, prod(v_lv));
    return Unit;
}

unit_t scalarProd_part_14()
{
    vec_int_t v_mv;
    v_mv = q_vec_int_get(&ch13);
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    q_vec_int_put(&ch29, prod(v_mv));
    return Unit;
}

unit_t scalarProd_part_15()
{
    vec_int_t v_nv;
    v_nv = q_vec_int_get(&ch14);
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    q_vec_int_put(&ch30, prod(v_nv));
    return Unit;
}

unit_t scalarProd_part_16()
{
    vec_int_t v_ov;
    v_ov = q_vec_int_get(&ch15);
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    q_vec_int_put(&ch31, prod(v_ov));
    return Unit;
}

void * fun_thread_1(void * arg)
{
    scalarProd_part_1();
    return NULL;
}

void * fun_thread_2(void * arg)
{
    scalarProd_part_2();
    return NULL;
}

void * fun_thread_3(void * arg)
{
    scalarProd_part_3();
    return NULL;
}

void * fun_thread_4(void * arg)
{
    scalarProd_part_4();
    return NULL;
}

void * fun_thread_5(void * arg)
{
    scalarProd_part_5();
    return NULL;
}

void * fun_thread_6(void * arg)
{
    scalarProd_part_6();
    return NULL;
}

void * fun_thread_7(void * arg)
{
    scalarProd_part_7();
    return NULL;
}

void * fun_thread_8(void * arg)
{
    scalarProd_part_8();
    return NULL;
}

void * fun_thread_9(void * arg)
{
    scalarProd_part_9();
    return NULL;
}

void * fun_thread_10(void * arg)
{
    scalarProd_part_10();
    return NULL;
}

void * fun_thread_11(void * arg)
{
    scalarProd_part_11();
    return NULL;
}

void * fun_thread_12(void * arg)
{
    scalarProd_part_12();
    return NULL;
}

void * fun_thread_13(void * arg)
{
    scalarProd_part_13();
    return NULL;
}

void * fun_thread_14(void * arg)
{
    scalarProd_part_14();
    return NULL;
}

void * fun_thread_15(void * arg)
{
    scalarProd_part_15();
    return NULL;
}

void * fun_thread_16(void * arg)
{
    scalarProd_part_16();
    return NULL;
}

vec_int_t scalarProd(vec_int_t v_pv)
{
    pthread_t thread1;
    pthread_t thread2;
    pthread_t thread3;
    pthread_t thread4;
    pthread_t thread5;
    pthread_t thread6;
    pthread_t thread7;
    pthread_t thread8;
    pthread_t thread9;
    pthread_t thread10;
    pthread_t thread11;
    pthread_t thread12;
    pthread_t thread13;
    pthread_t thread14;
    pthread_t thread15;
    pthread_t thread16;
    pthread_create(&thread1, NULL, fun_thread_1, NULL);
    pthread_create(&thread2, NULL, fun_thread_2, NULL);
    pthread_create(&thread3, NULL, fun_thread_3, NULL);
    pthread_create(&thread4, NULL, fun_thread_4, NULL);
    pthread_create(&thread5, NULL, fun_thread_5, NULL);
    pthread_create(&thread6, NULL, fun_thread_6, NULL);
    pthread_create(&thread7, NULL, fun_thread_7, NULL);
    pthread_create(&thread8, NULL, fun_thread_8, NULL);
    pthread_create(&thread9, NULL, fun_thread_9, NULL);
    pthread_create(&thread10, NULL, fun_thread_10, NULL);
    pthread_create(&thread11, NULL, fun_thread_11, NULL);
    pthread_create(&thread12, NULL, fun_thread_12, NULL);
    pthread_create(&thread13, NULL, fun_thread_13, NULL);
    pthread_create(&thread14, NULL, fun_thread_14, NULL);
    pthread_create(&thread15, NULL, fun_thread_15, NULL);
    pthread_create(&thread16, NULL, fun_thread_16, NULL);
    return scalarProd_part_0(v_pv);
}
